version: '3.8'

services:
  verifier:
    build: .
    command: ./verifier
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    networks:
      - app-network

  holder:
    build: .
    command: ./holder
    depends_on:
      - verifier
    environment:
      - RUST_LOG=info
    networks:
      - app-network

networks:
  app-network:
    driver: bridge